<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260210102123 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE "order" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE product ADD my_order_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE product ADD CONSTRAINT FK_D34A04ADBFCDF877 FOREIGN KEY (my_order_id) REFERENCES "order" (id)');
        $this->addSql('CREATE INDEX IDX_D34A04ADBFCDF877 ON product (my_order_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE "order"');
        $this->addSql('ALTER TABLE product DROP CONSTRAINT FK_D34A04ADBFCDF877');
        $this->addSql('DROP INDEX IDX_D34A04ADBFCDF877');
        $this->addSql('ALTER TABLE product DROP my_order_id');
    }
}
